### PR TITLE
Add a changeset to Delete coded obs with null values from the summary page encounters

### PR DESCRIPTION
**Pull request by ssmusoke**
most of these seem to be health education related concepts which are not on the summary page. This issue was faced in Kisugu during the field testing of MCH forms

### CODE REVIEW

**Comment by dkayiwa** [comment]
Do you guys review these pull requests? They have too many commits, making it harder to review. 😊

**Comment by ssmusoke** [comment]
@dkayiwa we tend to focus on the changed files not the actual commits and use the merge squash functionality

**Comment by dkayiwa** [comment]
It takes efforts for some one like me to look through all these commits for changed files. I wonder why you guys do not fix this? For it is just a matter of pulling the latest upstream changes. Most of your pull requests are like this. ☺️

**Comment by ssmusoke** [comment]
@dkayiwa Got you let me close this PR and clean it up

**Pull request closed without merging**
