### PR TITLE
Validation hiv care dates

### PR DESCRIPTION
**Pull request by slubwama**
https://trello.com/c/fq1AmGxg/247-validation-hiv-care-dates

### CODE REVIEW

**Comment by ssmusoke** [comment]
@slubwama no validation message is shown, for each getField call you need to show the error span for the field

**Comment by slubwama** [comment]
@ssmusoke  if you mean this getField(prime + '.error').html(message_to_throw).show();
message_to_throw is the message. prime + '.error' is the field where the message to throw is directed to. I this I have done that already

**Comment by slubwama** [comment]
That should work

**Comment by ssmusoke** [comment]
@slubwama Eligible for ART is now a required field, yet it is not required for eligible and ready.

**Comment by ssmusoke** [comment]
@slubwama 

1. Date confirmed positive is not validated to be after HIV enrolled date 

2. Global messages - use the same labels as the fields so that the users can connect 

3. When ART start date is after HIV enrolled date, but before eligible date - the message shown is "ART start date must be after Enrolled date" instead of "ART start date must be after the eligible for ART date"

4. When ART start date is after HIV enrolled date, but before eligible and ready date when the eligible date is not there - the message shown is "ART start date must be after Enrolled date" instead of "ART start date must be after the eligible and ready for ART date"

5. The date substituted in first line can be before the ART start date 

6. The date switched to second line can be before the ART start date

**Comment by slubwama** [comment]
@ssmusoke why are you contradicting your self. https://trello.com/c/fq1AmGxg/247-validation-hiv-care-dates
5 & 6 here compare them with 8,9 & 10. where are you getting these rules. have you consulted any source??
1 is fine

**Pull request merged**
