### PR TITLE
Smc card issues 1.0.14

### PR DESCRIPTION
**Pull request by slubwama**

### CODE REVIEW

**Comment by ssmusoke** [comment]
@slubwama There is a travis failure. This PR should not include MarkPatientAsDead.gsp and MarkPatientAsDeadTest.java classes since they are in a separate PR.

**Comment by ssmusoke** [comment]
@slubwama 

1. How did you hear about SMC has Other Other Specify (text). Also move Other Specify to its own line so that it is clear 

2. Client HIV test results: the radio for HIV+ should only be selectable if the HIV+ value is selected

3. Assistant circumciser shows all providers - encounter provider does not match uuid values for the role 

4. C5: BP requires 2 values not one, see ART Encounter card 

5. C5: Urethra discharge values should not be caps 

6. Type of circumcision Procedure put size input and text on the same line - there is space 

7. Cadre - needs to be a drop down, see mapping of TB form by intellisoft 

8. Post Operation Mangement: BP has to be 2 fields separated by a / 

9. How do I access the followup form?

**Comment by ssmusoke** [comment]
@slubwama 

1. Section B: Care Entry Point - Other Specify hides and appears yet other fields are shown and disabled

2. Section B: Other and Other specify are duplicated - text should be Other Specify and the text field should have no label 
3. C5: Open Wounds/ healed scars - the No option is on 2 different lines yet there is space on the form 

4. Name of Circumciser - use EncounterProvider instead of Encounter Provider and role which is not required

5. Name of Circumciser and assistant are required (shown by the red *) but they are not validated on form submission - you can submit a form without entering them

**Comment by slubwama** [comment]
comment 4 I have researched and its the best way how to put two providers on the same page

**Comment by ssmusoke** [comment]
@slubwama the first has to be just a provider and any additional can be encounterProviderAndRole

**Comment by ssmusoke** [comment]
@slubwama There is still a conflict in the pom.xml

**Pull request merged**
