### PR TITLE
WIP: Hmis078 postnatal encounter form

### PR DESCRIPTION
**Pull request by moshonk**
@ssmusoke, kindly review this. cc @ningosi 

All the comments have been worked on as below:

Mother’s Information 
1. Family Planning Given – should allow the selection of multiple options 
2. Status of the Cervix
· Add an option Not Done 
· Make this a required field 
3 Septrin should only be available for those patients who are HIV+
4. Remove Vitamin A from the list 

HIV Information 
1. Make this section a fieldset outside mother’s information 
2. EMTCT code for partner should not be a required field as the partner status may not be known 

Diagnosis 
1. Make this section a fieldset outside mother’s information
2. This is currently copied from Maternity form so needs to be updated
3. The METS team will provide a list of common Postnatal diagnoses to add to this list

Routine Administration 
1. Remove Vitamin A 

Child’s Information 
1. Change the title to “Baby Information” 
2. MUAC  - a field for the MUAC measurement 
3. Status of Baby – add a description for the codes 

Referral Information 
1. Add a row for the mother and the child 
2. Change the titles of the fields as follows (need to make this a merged table cell):
· Referred From
o Facility Name 
o Facility Type 
· Referred to 
o Facility Name
Facility Type

### CODE REVIEW

**Comment by ningosi** [comment]
@moshonk Please resolve those conflicts and commit for review

**Comment by ningosi** [comment]
@moshonk ressovle those conflicts

**Comment by moshonk** [comment]
@ningosi Conflicts resolved

**Comment by ningosi** [comment]
@ssmusoke please find time to look into this

**Comment by ssmusoke** [comment]
@ningosi Have you gone over the issues that I raised as fixed?

**Comment by ssmusoke** [comment]
@moshonk Error Cannot find concept for value 164438AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA in conceptId attribute value. Parameters: {conceptId=164438AAAAAAAAAAAAAAAAAAAAAAAAAAAAAA}

**Comment by moshonk** [comment]
@ssmusoke The issues on this form have been rectified. Please check it out cc @ningosi

**Comment by ssmusoke** [comment]
@moshonk 

1.  A PNC encounter can be entered without a Maternity encounter so remove the check at the top of the form

2. HIV+ patients still have the ability to select HIV- on the column 

3. HIV information is not disabled for HIV- patients 

4. Routine Administration - see other forms where the HIV information is meant to be disabled

**Comment by moshonk** [comment]
@ssmusoke, This ready for review, all issues fixed. cc @ningosi

**Comment by ningosi** [comment]
@ssmusoke any pending issues on this PR? @moshonk fixed issues you raised

**Pull request merged**
