### PR TITLE
WIP:Hmis096a tb register summary page

### PR DESCRIPTION
**Pull request by moshonk**

### CODE REVIEW

**Comment by moshonk** [comment]
@ssmusoke I have updated the form with the following issues addressed. I have also updated the demo concept dictionary with relevant concepts. So you can now preview the form @ningosi 

Cadre of Health Worker
  · Separate Doctor and Clinical Officer
  · Add Dentist 
  · Rename Pharmacist to Dispense 
  · Change Lab Technician to Lab Personnel 
2. Add relationship for contact person as per register 
3. Add code for Type of Patient
4. Add code for Disease Classification 
5. When the Transfer In From field is filled with the name of the facility the Unit TB No. field is not enabled 

Results of Spatum and Other Examinations 
1. Sputum smear results, put the values of in the Registers 
· Remove Scanty, Positive and Contaminated Specimen 
· Add the +, ++, and +++ along with their descriptions 
2. Make Pre-RX its own fieldset with the title “Pre-RS Spatum Smear”
3. The spartum smear results are only required when the disease classification is Pulmonary clinically diagnosed TB 
4. Make Other Investigations its own fieldset 
5. Other Investigations: 
· Make each investigation have its own row 
· Add codes for GeneXpert results 
· Xray – change the results to checkboxes as multiple results are possible  
6. HIV Counselling and testing options are only for the HIV- patients – read the register on the SOP to handle HIV+ patients (have an ART summary page encounter date which is before the TB Summary Page encounter) 

Treatment Model 
1. Add the codes for Treatment models 

Treatment Outcome 
1. Treatment Outcome – add not Evaluated

**Comment by ssmusoke** [comment]
1. Put Name of Contact and Relationship of Contact person on the same line (move name to the next row) 
2. Spartum results + should be 1--99 AFB/100 Fields 
3. GeneXpert - the refampicine codes are not selectable they are just descriptions of the codes see Register footer (I think you need to use an HTML entity for the comma)  
3. Xray has other without a text field to enter other  results 
4. Change form name to "HMIS 096A Health Unit TB Form - Summary"
5. HIV Counseling and Testing - HIV+
- Is Patient on CPT and Is Patient on ART should be available for selection 
- HIV testing and results should not be enabled since the patient is already on ART 
6. Treatment Model labels
- F - Facility COTS 
- C - Community COTS (CBDOTS)

**Comment by moshonk** [comment]
@ssmusoke This is ready for review

**Comment by ssmusoke** [comment]
@moshonk 

1. Spatum examination date should be required when spartum results other than Not done are selected

**Comment by moshonk** [comment]
@ssmusoke. This comment has been worked upon. Please check it out

**Comment by ssmusoke** [comment]
@moshonk Run into a missing concept java.lang.IllegalArgumentException: Cannot find concept for value 164831 in answerConceptIds attribute value. Parameters: {answerConceptIds=162592,162591,164831,1577,1578,1555,163557,164914,5622, answerLabels=Clinical officer,Doctor, Laboratory Personnel, Nurse, Midwife, Community Health Worker,Dispenser,Dentist,Other, conceptId=1783AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA, id=cadre-of-health-worker}

**Pull request merged**
