### PR TITLE
Fixing problem where patients are not exited from programs

### PR DESCRIPTION
**Pull request by dkayiwa**

### CODE REVIEW

**Comment by ningosi** [comment]
@ssmusoke try pulling this in and see if the problem got ressolved

**Comment by ssmusoke** [comment]
@ningosi There was a problem with the TB summary form which @moshonk is working on

**Comment by ssmusoke** [comment]
@dkayiwa See this https://pastebin.com/NTeKCGtt which is gotten by @moshonk on Editing a TB summary form cc @ningosi

**Comment by ssmusoke** [comment]
@dkayiwa Just confirmed that this issue is present on the code in this PR too - when I enter  a final outcome as part of the summary page I get https://gist.github.com/ssmusoke/3f44477efe0bb976e582391d07e7b27b

**Comment by ssmusoke** [comment]
@dkayiwa You have merged but the code is broken

**Comment by dkayiwa** [comment]
I merged because those changes were not the source of the NPE

**Comment by dkayiwa** [comment]
Here is a followup pull request https://github.com/METS-Programme/openmrs-module-aijar/pull/257

**Comment by dkayiwa** [comment]
I merged the earlier pull request to force you review and merge the fix immediately. 😊

**Pull request merged**
