### PR TITLE
Setting completion date and outcome instead of voiding for program exits

### PR DESCRIPTION
**Pull request by dkayiwa**

### CODE REVIEW

**Comment by ssmusoke** [comment]
@dkayiwa Is it possible to merge the MCHProgram enrollment and exit into a single class that handles both as TB.

**Comment by dkayiwa** [comment]
Of course it is possible to merge them. But i will merge after sharing my thoughts.

1) Generally, a class should not do more than it should. :)
2) Merging them will make the class unnecessarily more complicated.
3) The likely hood of bugs will increase because for instance if there is a problem with exits, one may  accidentally introduce a bug in enrolments because the code is in the same class. Not forgetting the fact that MCH exit only forms will now have a postsubmission action class that does more than exits, bit also enrollments which they do not need. The same goes for MCH enrollment forms that also will now have a postsubmission action class that deals with exits that they do not need.
4) I will only add this if you think the first three are not convincing enough. 😊

**Comment by ssmusoke** [comment]
@dkayiwa 

1. The TB class is already doing this 

2. Yes it will make the class more complex, but will still be one class just like TB in #1 above 

3. TB form already does this 

4. For the future, there may be forms like Maternity which will have both enrollment and exit on the same form.

**Comment by dkayiwa** [comment]
TB form is doing this because its current usage is different from MCH. And the fact that it is already doing it does not necessarily mean we did the best design. If time allowed, it would have been better for even TB to have different classes instead of the same class being overloaded with the same responsibility.

As for (4.) i will lookup an article from Martin Fowler where he says if you find yourselves saying things like, "in future, we many need this", then you may be going a wrong path. He insists that even if you may need it in the future, wait for that future to come. 😊

**Comment by ssmusoke** [comment]
@dkayiwa Oh yes that future is already here hence the need. If HTML Form Entry allowed for multiple post submission actions then the classes would be simpler but it does not ...

**Comment by dkayiwa** [comment]
When you say that future is now here, do you mean the current classes do not address the current use cases?

**Comment by ssmusoke** [comment]
@dkayiwa  The current classes may not support a situation where MCH is a program enrollment avenue, which is a 50/50 possibility to be confirmed in the next 2-3 weeks

**Comment by dkayiwa** [comment]
Martin Fowler say that you would wait until when that happens. 😊

**Comment by ssmusoke** [comment]
@dkayiwa Martin does not write code under pressure with facility staff

**Comment by dkayiwa** [comment]
But he has dealt with developers like you who are under pressure from facility staff.
From such years of experience that he has, he says that wait for when you confirm this requirement, before you can actually get to implement it. I do not usually go against such advice unless am convinced otherwise. 😊

**Comment by dkayiwa** [comment]
Also remember that developer time is very expensive. You do not want to pay for it until when you are 100% sure it is needed. 😊

**Comment by ssmusoke** [comment]
@dkayiwa I am 100% sure it is needed which is why I am asking for it

**Comment by dkayiwa** [comment]
The answer lies in this:

The current classes may not support a situation where MCH is a program enrollment avenue, which is a 50/50 possibility to be confirmed in the next 2-3 weeks

**Comment by ssmusoke** [comment]
@dkayiwa The shouldEnrollAndExitPatientFromTBProgramWhenNewTBFormIsSubmittedWithTreatmentOutcome exists twice in the TBProgramPostSubmissionActionTest class

**Comment by dkayiwa** [comment]
Do you mind giving me the line numbers where the first one is and the second?

**Comment by ssmusoke** [comment]
@dkayiwa Run an mvn clean install or any build on the test class and it will show you the offending methods

**Comment by dkayiwa** [comment]
I always run mvn clean install before committing. The build has always been successful. Or did i misunderstand you?

**Comment by ssmusoke** [comment]
@dkayiwa  Looks like my git is the one that messed up merging the changes

**Pull request merged**
