### PR TITLE
WIP:HMIS096a-TBRegister-Followup(Encounter)

### PR DESCRIPTION
**Pull request by moshonk**
Added TB Register followup(Encounter) Form Implementation

### CODE REVIEW

**Comment by ssmusoke** [comment]
1. Issue of Anti-TB drug - the phase is a required field currently is not validated 

2. Name of drug - can you make this field larger as there is space (add does not need to take that much space)

3. Duration of treatment - put some space between the number and frequency (they are currently touching and confusing) 

4. Form cannot save because of a missing EncounterType 

5. Instead of MUAC/z-score change the title to vitals. 

6. INR number is currently disabled when is it entered?

**Comment by ssmusoke** [comment]
@moshonk 

1. I should not be able to enter a TB Follow up form without a TB Summary form entered (Look at ART Encounter)

2. Change the form name and page title to "HMIS 096A Health Unit TB Form - Followup" (watch the captialization)

**Comment by moshonk** [comment]
@ssmusoke , It's done.

**Comment by ssmusoke** [comment]
@moshonk Let me review

**Pull request merged**
