### PR TITLE
WIP:Hmis031-opd-register

### PR DESCRIPTION
**Pull request by moshonk**
@ssmusoke,@ningosi Please find the OPD form for your review. I am yet to change the Concept Ids on the form to UUIDs. I would like you guys to review this first before I can change them. I would find it easier to deal with concept IDs  rather than UUIDs if there's a correction to be made. @ningosi

### CODE REVIEW

**Comment by slubwama** [comment]
@moshonk  please resolve conflicts.

**Comment by ssmusoke** [comment]
@moshonk 

1. As per the TB clinic - do not add the locations and encounter types as part of the MDS files - use the classes to install the encounter types and locations 

2. There is a conflict in the CSS file - please update so that I can review

**Comment by moshonk** [comment]
@ssmusoke Noted. The conflict has been resolved.

**Comment by ssmusoke** [comment]
@moshonk Do look at the comment on the metadata files

**Comment by moshonk** [comment]
@ssmusoke I have updated the code based on comments on the metadata files

**Pull request merged**
