### PR TITLE
EMTCT Module Integration forms 

### PR DESCRIPTION
**Pull request by ssmusoke**

### CODE REVIEW

**Comment by ssmusoke** [comment]
@slubwama updated as requested

**Comment by slubwama** [comment]
@ssmusoke this breaks the build when I do an mvn clean install. It doesnt build due to the changes you added of upgrading openmrs-core to 2.0.6

**Comment by slubwama** [comment]
@ssmusoke find attached stack trace https://pastebin.com/MwqSysba

**Comment by ssmusoke** [comment]
@slubwama this is not the root cause of the failure, do check higher up in
the stack trace for what causes the AIJAR module startup to fail

**Comment by slubwama** [comment]
@ssmusoke Thats all I get. did you test this well before the PR. I suggest you do the following testing approaches. 
1. Test when upgrading from 2.0.5 to 2.0.6 openmrs platform
2. Test when you have this server instance created basing on the latest of this modulle

**Comment by ssmusoke** [comment]
@slubwama what is the actual error that you run into? It works well on my
machine

**Comment by slubwama** [comment]
@ssmusoke hope this is helpful https://pastebin.com/aU8xnibQ

**Comment by ssmusoke** [comment]
@slubwama Had you run the UgandaEMR concept script on your server? Since
this does not specify which concept name is giving the error does not mean
that it is within the PR submitted

**Comment by slubwama** [comment]
@ssmusoke yes I did run it several times. And every time I get the same results.

**Comment by ssmusoke** [comment]
@slubwama I have been able to run this properly using a database created using the new-install.sql script created in the tools target folder which is included in the installer.

**Comment by slubwama** [comment]
@ssmusoke this is what happened when I go your way https://pastebin.com/Shf2KBRZ

**Comment by slubwama** [comment]
@ssmusoke  please provide a link of the Ticket to this PR.

**Comment by ssmusoke** [comment]
https://trello.com/c/lwgyLsJJ

**Comment by slubwama** [comment]
@ssmusoke 
1.Please make sure that when you select phone on the appointment form or sms on Followup Type section  enable and disable the respective fields outcome section. 
2. Why has the visit list disappeared on the patient dashboard

**Comment by ssmusoke** [comment]
@slubwama The PR is not complete (see email shared on the subject), wanted
to get feedback to ensure that I was not misfiring before continuing work
on it

**Pull request merged**
