### PR TITLE
Relationship between the infant and mother 

### PR DESCRIPTION
**Pull request by ssmusoke**
This is the relationship tag between the mother and infant - however it does not work on my setup @slubwama @carapai @jmpango Please can you help me verify this on your local installations. All you need to do is to copy this version of the EID Summary page form

### CODE REVIEW

**Comment by slubwama** [comment]
This doesn't work here too. correct it.

**Comment by ssmusoke** [comment]
@slubwama I never said that it works, I was just wondering if it was my local setup

**Comment by slubwama** [comment]
So why did you put it in a pull request.

**Comment by ssmusoke** [comment]
@slubwama How else would you get access to the changes that I wanted you to see?

**Pull request closed without merging**
