### PR TITLE
WIP: Hmis031 opd register

### PR DESCRIPTION
**Pull request by moshonk**

### CODE REVIEW

**Comment by moshonk** [comment]
@ssmusoke, This is ready for review. I have worked on the following:
1. Malaria 
. When a test is not done, the Not Done value should be selected for results and should not be changeable  
2. New Diagnosis 
. The drop down search for diagnoses does not work 
3. Disability
. Added type of disability

**Comment by ssmusoke** [comment]
@moshonk 

1. Malaria 
- When a user selects not done the results should automatically select not done
- When a user selects a test not done should not be available as an option

2. TB 
- Lab results should only be available when a patient is sent to the lab hence the checkbox selected 

3. Type of disability still has no data 

4. New Diagnosis - should come from a list from HMIS 105a, and needs to have a section Other Specify for those diagnoses not included in the report - some of the options do not make sense

**Comment by moshonk** [comment]
@ssmusoke, This is now for review.

**Comment by ssmusoke** [comment]
1. The register has no provider so remove this field 

2. Diagnosis does not have other specify which should always be displayed so that any diagnoses that do not match are added 

3. Nothing has changed on this form since I last looked at it!!!!

4. I see 2 forms 031-OutPatientRegister.xml and 031-OpdRegister.xml - which one works

5. This PR has changes to the following files which should not be - why?
  - Concepts_TB-1.xml
  - 122a-HIVCare_ARTCard-SummaryPage.xml

**Comment by ningosi** [comment]
@ssmusoke find time to review this

**Comment by ssmusoke** [comment]
@ningosi Have you checked the issues that I raised and verified that they have been fixed?

**Comment by moshonk** [comment]
@ssmusoke, I have reset the branch. So the issues raised above have now been resolved

**Comment by ssmusoke** [comment]
@moshonk just checking to ensure there is another set of eyes from @ningosi

**Comment by ssmusoke** [comment]
@moshonk 

1. Change form name and title to "HMIS 031 Outpatient(OPD) FORM" add a space between outpatient and the opening brace 

2. Date field has the label "Date*Follow up visit date:"

3. First and last rows remove the columns that are not used

4. Diagnosis - increase the width of the diagnosis field so that the text appears there is sufficient space on the row 

5. Drugs/Treatment 
  - the Add|remove links break on 2 lines, ensure they remain on the same line 
  - A space is needed between the field for duration and the drop down for frequency (I have raised this before)

**Comment by moshonk** [comment]
@ssmusoke Please check this out. I have worked on the comments cc @ningosi

**Pull request merged**
