### PR TITLE
WIP: Hmis096a tb register followup page

### PR DESCRIPTION
**Pull request by moshonk**

### CODE REVIEW

**Comment by moshonk** [comment]
@ssmusoke, I have updated the demo server so you should be able to preview the changes below

Results of Sputum and Other Examinations 
1. Sputum Smear results - See Summary page 
2. Drug Susceptibility Testing – add codes 

Vitals
1. Disable MUAC for patients below 6 months of age 
2. Add a MUAC values field

Issue of Anti-TB Drugs 
1. METS will provide the list of drugs and drug combinations - Added RHZE and RHZ drugs
Vitals MUAC we need to add SIZES*

**Comment by ssmusoke** [comment]
MUAC not disabled for babies below 6 months old https://www.dropbox.com/s/bsacwve0d4o6rh4/Screenshot%202017-05-16%2017.30.47.png?dl=0

**Comment by moshonk** [comment]
I think that's correct. MUAC is only available for babies aged 6 months and
below. It's disabled for anyone aged above 6 months.

Regards

Ken Omondi
Skype: omondi.ken84
Twitter: @moshonk
Yahoo: kenneth_omondi@yahoo.com

**Comment by ssmusoke** [comment]
@moshonk MUAC is only for 6 months and above mainly because the changes below 6 months are so rapid that it s not a reliable measure - check the documentation that I sent

**Comment by moshonk** [comment]
@ssmusoke This is ready for review

**Pull request merged**
