### PR TITLE
WIP:HMIS071-Integrated-Antenatal-Encounter-Form

### PR DESCRIPTION
**Pull request by moshonk**
Updated based on form review comments
Made Cosmetic updates to the UI
Added Form Validations
@ssmusoke Please find this PR for the ANC form
cc @ningosi

### CODE REVIEW

**Comment by ssmusoke** [comment]
1. Gestational age is not shown in weeks and is negative for a date before today and due to that error Timing is also not correct. 

2. Disabled fields are not greyed out in a darker color 

3. HIV status needs to work like the maternity form including the EMTCT codes 

4. Diagnosis - use checkboxes to show the different diagnoses. Other Specify needs to be a text area in a single line 

5. Routine administration:
* ARVs given should only be for HIV+
*  Infant feeding - is currently broken to 2 lines, its okay to have it like Maternal nutrition counseling
* Family Planing Counseling - use two columns to fit well
* Folic Acid - move to next row to be the same line as # of tablets given 
* Other treatments - use two columns and a text field to smooth out the table 
9.

**Comment by moshonk** [comment]
@ssmusoke I haven't understood point 1.

**Comment by ssmusoke** [comment]
@moshnok https://www.dropbox.com/s/d26sv9oqgdhlns8/Screenshot%202017-04-25%2011.27.52.png?dl=0

**Comment by moshonk** [comment]
@ssmusoke. I've just looked at it. It works fine on my side.  http://i.imgur.com/mSVBzR4.jpg
Are you getting any javascript errors?  
Kindly send me a screenshot of the whole form at the point when you are capturing the LMP value. I'd like to look at the format of the Encounter date.

**Comment by ssmusoke** [comment]
@moshonk You were right my encounter date is way back in the past...

**Comment by moshonk** [comment]
@ssmusoke Great!

**Pull request merged**
