### PR TITLE
WIP: Hmis 074 INTERGRATED FAMILY PLANNING FORM

### PR DESCRIPTION
**Pull request by jwnasambu**

### CODE REVIEW

**Comment by slubwama** [comment]
Thanks for the PR will be reviewed later.

**Comment by jwnasambu** [comment]
Thanks sir, as a group we truly appreciate the effort.

**Comment by dkayiwa** [comment]
The commit messages need to say what exactly the commit is for, instead of just something like "Second commit, Third commit, etc"

**Comment by jwnasambu** [comment]
k

**Comment by jwnasambu** [comment]
Please Review These Changes.

**Pull request closed without merging**
