### PR TITLE
Add Health Facility Name to the Login Credentials 

### PR DESCRIPTION
**Pull request by solemabrothers**

### CODE REVIEW

**Comment by ssmusoke** [comment]
@solemabrothers instead of the static export for MODULE_ID, I suggest you add a constant GP_HEALTH_FACILITY_NAME and use that

**Comment by solemabrothers** [comment]
> 
> 
> @solemabrothers instead of the static export for MODULE_ID, I suggest you add a constant GP_HEALTH_FACILITY_NAME and use that

@ssmusoke GP_HEALTH_FACILITY_NAME  is already exisiting which is the variable holding MODULE_ID + ".healthCenterName";

Take look at this line `public static final String GP_HEALTH_CENTER_NAME = MODULE_ID + ".healthCenterName";`

**Comment by ssmusoke** [comment]
@solemabrothers I do not see any constant defined as GP_HEALTH_CENTER_NAME - where is it? You are doing string concatenation in the class which is a bad idea when the constant shall be reused in multiple places

**Comment by solemabrothers** [comment]
> 
> 
> @solemabrothers I do not see any constant defined as GP_HEALTH_CENTER_NAME - where is it? You are doing string concatenation in the class which is a bad idea when the constant shall be reused in multiple places

@ssmusoke to be honest I do not understand what you mean, the constant was defined here https://github.com/METS-Programme/openmrs-module-aijar/blob/6fddd8fc903fe41be5b2e25d3cb89f1d13b6c13c/api/src/main/java/org/openmrs/module/aijar/AijarConstants.java#L17 and that's the way to retrieve it. I did not write that constant it was already existing

**Comment by ssmusoke** [comment]
@solemabrothers then just use the constant GP_HEALTH_CENTER_NAME in the code and let IntelliJ make the right import

**Pull request merged**
