### PR TITLE
Wip:Global-Resources

### PR DESCRIPTION
**Pull request by moshonk**
Made the following changes to the aijar.css file:
- Added media query definitions for screen widths <1400 px
- Updated  the CSS so that definitions for non-data collection forms  (e.g. login form) are not broken by the introduction of global data collection form CSS definitions

Fixes the following issues:

1. Legends - can they be styled to be bold so that they stand out
2. Delivery: Preterm is on a new line you may need to add answerSeparator="" to all radio buttons
3. The right hand side of the tool is not straight - different lengths

### CODE REVIEW

**Comment by ssmusoke** [comment]
@moshonk you have a conflict that needs to be resolved

**Comment by ssmusoke** [comment]
@moshonk Please delete the grep file which is included in this PR

**Comment by moshonk** [comment]
@ssmusoke I have resolved the conflicts. It's ready now.

**Comment by ssmusoke** [comment]
@moshonk see comment above

**Comment by moshonk** [comment]
@ssmusoke grep file deleted

**Comment by ssmusoke** [comment]
@moshonk I had to revert this PR since it was breaking forms on other pages ... So please can you create a new PR with these changes limited to just forms

**Pull request merged**
