### PR TITLE
Platform 2.2.0 - Update module versions to the latest reference application versions 

### PR DESCRIPTION
**Pull request by ssmusoke**

### CODE REVIEW

**Comment by ssmusoke** [comment]
@slubwama Where are you seeing the platform change? That was already merged

**Comment by ssmusoke** [comment]
@slubwama  FYI on the platform snapshot https://github.com/METS-Programme/openmrs-module-aijar/pull/460#discussion_r369939312

**Comment by slubwama** [comment]
@ssmusoke  when I pull down your changes
Core openmrs

**Comment by ssmusoke** [comment]
@slubwama This is because your local code is not up to date with upstream master - look at the changes in the PR and you will see the difference

**Comment by slubwama** [comment]
@ssmusoke here is the reference were this changed  https://github.com/METS-Programme/openmrs-module-aijar/blob/694c0f712c1ffb3eca474280233ed66a7faf9db4/pom.xml#L50

**Comment by ssmusoke** [comment]
@slubwama Read this https://github.com/METS-Programme/openmrs-module-aijar/pull/460#discussion_r369939312 (this is the second time I am posting the reference and rationale for the change)

**Comment by slubwama** [comment]
@ssmusoke  thanks for the clarity had missed that

**Comment by dkayiwa** [comment]
@slubwama you very very quickly understand, after a long explanation. 😊

**Pull request merged**
