### PR TITLE
[Reopened Issue] DSDM stability assessment not stable when there is DTG substitution.

### PR DESCRIPTION
**Pull request by slubwama**
Ticket https://app.asana.com/0/1116981488119523/1124012338753398

### CODE REVIEW

**Comment by slubwama** [comment]
@dbaluku  Kindly review

**Comment by slubwama** [comment]
@dbaluku ETA on the Review??

**Comment by solemabrothers** [comment]
@slubwama do you mind providing what the concern was from kawaala??

**Comment by slubwama** [comment]
@solemabrothers This PR was based on the Kawaala concerns.

**Comment by dbaluku** [comment]
@slubwama  a change of current regimen  on the encounter form to a DTG regimen changes the stability to unstable immediately  on that form.

**Pull request merged**
