### PR TITLE
Add the ability to show patient status information on the dashboard based on information entered 

### PR DESCRIPTION
**Pull request by ssmusoke**
Travis will throw an error until this PR on patient flags is merged https://github.com/openmrs/openmrs-module-patientflags/pull/8

### CODE REVIEW

**Comment by ssmusoke** [comment]
@slubwama @carapai For review and comments 

There are 14 status values in total: 

Status | Color
-- | --
Next Appointment on 15 September 2017 | Green
Due for Initial Load in next month | Green
Overdue for Initial viral load from October 1, 2017 | Red
Due for routine Load in next month | Green (caters for children 6 months and adults 12 months)
Overdue for routine Load from July 10, 2017 | Red (caters for children 6 months and adults 12 months)
Missed Appointment on August 28, 2017 | Orange
Lost since August 31, 2017 | Red
Lost to Follow-up since July 18, 2017 | Red
Due for 1st DNA PCR on June 1, 2017 | Green
Overdue for 1st DNA PCR from June 1, 2017 | Red
Due for 2nd DNA PCR on July 4, 2017 | Green
Overdue for 2nd DNA PCR from July 4, 2017 | Green
Due for Rapid Test on July 6, 2017 | Green
Overdue for Rapid Test from July 6, 2017 | Green

The following are still pending:
- Due for TB sputum test on September 7, 2017 | Green
- TB Sputum test overdue | Red
- Viral Load due to ANC visit

**Comment by carapai** [comment]
@ssmusoke ,
I have tried to pull and build but tell me Could not resolve dependencies for project org.openmrs.module:aijar-api:jar:2.0.1-SNAPSHOT: Failed to collect dependencies at org.openmrs.api:openmrs-api:jar:2.0.6
check this pastebin 
https://pastebin.com/bRGYdkGn

**Comment by carapai** [comment]
@ssmusoke ,
All openmrs modules are now not compiling

**Comment by carapai** [comment]
@ssmusoke ,
I have gotten this error, seems like some metadata is failing to install
Check
https://pastebin.com/Ps8JN4Ew

**Pull request merged**
