### PR TITLE
Revert "Add the ability to show patient status information on the dashboard based on information entered "

### PR DESCRIPTION
**Pull request by slubwama**
Reverts METS-Programme/openmrs-module-aijar#31
@ssmusoke I am reverting the PR. I merged it but realised that all javascript logic in forms breaks due to this PR. Look into the broken js

### CODE REVIEW

**Comment by ssmusoke** [comment]
@slubwama this PR is well formed even during your your testing. If you don't deploy the new 2.0.6 OpenMRS module it will be broken...

The demo server with these changes works fine

**Comment by slubwama** [comment]
@ssmusoke  I have just checked the Demo Server actually the JS is broken please look into it

**Comment by ssmusoke** [comment]
What JS specifically is broken do that I can reproduce?

**Comment by ssmusoke** [comment]
@slubwama Found the issue need to bump up HTML Form Entry to 3.6.0 will be sending a separate PR for that so you can close this one

**Pull request closed without merging**
